### ISSUE TITLE
TypeError [ERR_INVALID_ARG_VALUE]

### ISSUE THREAD

**Issue by jimmybreeze** [lightpohl/podcast-dl#42] opened 2023-01-30 02:59 UTC
Hello again!

Thanks for the new Windows binaries.

Unfortunately, I am getting this error. It works again when I revert back to v6.1.0.

```
.\podcast-dl-win-x64.exe --url "https://omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/A41BD365-C6BC-4966-9AC2-AE28005326F5/6097C5B8-233A-45BF-8F11-AE2800532703/podcast.rss" --episode-template "{{podcast_title}} - {{title}}"
internal/modules/cjs/loader.js:1089
      throw new ERR_INVALID_ARG_VALUE('filename', filename,
      ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:///home/joshua/code/podcast-dl/bin/bin.js'
←[90m    at createRequire (internal/modules/cjs/loader.js:1089:13)←[39m
    at C:\snapshot\dist\podcast-dl.js
    at C:\snapshot\dist\podcast-dl.js
    at Object.<anonymous> (C:\snapshot\dist\podcast-dl.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:863:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:708:14)←[39m
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'ERR_INVALID_ARG_VALUE'←[39m
}
```

**Comment by lightpohl** [comment] 2023-01-30 03:09
@jimmybreeze Ah! I think I know what the issue is — I built them with Node 12 instead of 14. Apologies, one moment!

**Comment by lightpohl** [comment] 2023-01-30 03:30
@jimmybreeze Okay! Fix is in — the Windows build did not like the `require` for the package version. Removed it and verified it on my Windows box. Should be good now if you download it again.

Thanks for the report!

**Closed by lightpohl** 2023-01-30 03:30 UTC

**Comment by lightpohl** [comment] 2023-01-30 03:38
Definitely let me know if you run into any more issues! Surprisingly tricky to transform the JavaScript into binaries. 😅
